spring:
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    # 服务器连接端口
    port: 6379
    #Redis数据库索引
    database: 0
    # Redis数据库连接密码
    password:
    jedis:
      pool:
        # 连接池最大连接数(负值表示没有限制)
        max-active: 20
        # 连接池最大阻塞等待时间(负值表示没有限制)
        max-wait: -1ms
        # 连接池中的最大连接池数
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间
    timeout: 1000